### ISSUE TITLE
Support numpy>=2.0

### ISSUE THREAD

**Issue by fire** [nmwsharp/robust-laplacians-py#18]
> With numpy>=2.0 the seg fault would occur, but downgrading to numpy==1.26.4 resolved the issue.

**Comment by bdpedigo** [comment]
also having this issue and would like to prefer to keep using numpy 2 - I'm wondering if bumping the version of pybind11 in `/deps` would fix this, I saw that `numpy.h` now looks like it has some logic to keep track of numpy 1 vs numpy 2 interfaces https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h

**Comment by nmwsharp** [comment]
Yes! Unfortunately numpy 2.0 introduced breaking changes that cause this. Recompiling with the latest pybind11 should resolve the issue and make it work with both pre-2.0 and post-2.0 numpy.

**Comment by bdpedigo** [comment]
Is this something that you'd be open to bumping in the `/deps` here so that future builds will recompile with more recent pybind11?

**Comment by nmwsharp** [comment]
Should be fixed as of right now! I bumped all of those dependencies for the rebuild I just did (CC our discussion in the other issue about py3.12).

However, it looks like the publish step failed, I'll have to deploy again. Should be on pypi in a few hours and we can check that this is resolved.

**Comment by nmwsharp** [comment]
Ok build succeeded, should actually work now if you pull `v1.0.0` from pypi. Please let me know if not!
