### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by bdpedigo** [nmwsharp/robust-laplacians-py#19]
Hi @nmwsharp - this package looks awesome and I'm hoping to use it for something, but noticed there are no Python 3.12 wheels available. 

I think the version of `cibuildwheel` you are using https://github.com/nmwsharp/robust-laplacians-py/blob/dd58b70da324ef8fb8554f91ad37f0eed4d85c2c/.github/workflows/build.yml#L61 

did not build for 3.12 by default, but newer ones will https://cibuildwheel.pypa.io/en/stable/changelog/#v2150

Wondering if you're open to bumping `cibuildwheel` to something newer, and rerunning the github action? I'm happy to open a PR or otherwise facilitate this.

**Comment by nmwsharp** [comment]
Yes, absolutely, I just haven't updated this lib since the 3.12 wheels were supported. I'd certainly appreciate a PR if you're interested to give it a try. Fair warning there is a ~50% chance that something we'll break and we'll need to put out a fire to get the builds to succeed after bumping cibuildwheel.

**Comment by bdpedigo** [comment]
great, just opened #20 - agree with your guess that it'll break something else, but happy to try to help with that if so

**Comment by nmwsharp** [comment]
Ok got the builds to succeed, kicked off a publish job now. If nothing goes wrong it should be on pypi in a few hours. Thanks! Feel free to reopen if anything seems wrong.

**Comment by bdpedigo** [comment]
it looks like the build succeeded but the publish to pypi failed https://github.com/nmwsharp/robust-laplacians-py/actions/runs/11938379378/job/33280576553

at a glance it looked like some issue with trusted publishers? let me know if I can help at all, but probably would be difficult for me without access to the repo

**Comment by nmwsharp** [comment]
Yep you got it right, forgot to set the trusted publisher :) Plus there was another small problem with having subfolders for the upload. Fixed now!

**Comment by bdpedigo** [comment]
Looks like it is working for me, I was able to install with numpy 2 and python 3.12 on a Mac. 

Many many thanks for getting this set up! I am using this for representation learning on neuron meshes
<img width="1390" alt="Screenshot 2024-11-15 at 4 12 27 PM" src="https://github.com/user-attachments/assets/8d5a796e-eeae-4c1b-b509-1ea0041d2f83">
and this is letting me avoid some annoying mesh fixing routines that don't work very well in practice, so it will be very useful for my research :)

P.S. I will of course cite you! thanks again

**Comment by nmwsharp** [comment]
Glad to hear it, so cool!!! Can't wait to see the research when it goes live :)
