### ISSUE TITLE
Cpp samles

### ISSUE THREAD

**Issue by petrasvestartas** [nmwsharp/robust-laplacians-py#2]
Hi,

Is there a C++ documentation besides python?

What dependencies are need for building on Windows Visual Studio x64?

**Comment by nmwsharp** [comment]
C++ code lives in this repo: https://github.com/nmwsharp/nonmanifold-laplacian

That repo is mainly structured around a simple GUI app, but that app should be easy to inspect for basic functionality. Feel free to file an issue there if you'd like more particular C++ examples!

(note that [a recent issue](https://github.com/nmwsharp/nonmanifold-laplacian/issues/2) in that repo indicates a few small changes are needed to compile in VS 2017. **update:** this should be resolved)

**Comment by nmwsharp** [comment]
Closing for now, feel free to reopen if you have more questions.
