### ISSUE TITLE
How do we implement mesh smoothing?

### ISSUE THREAD

**Issue by j20232** [nmwsharp/robust-laplacians-py#3]
## About

I'm now trying to apply `robust_laplacian` for mesh smoothing, but I cannot get the same result as [libigl](https://libigl.github.io/libigl-python-bindings/tut-chapter1/#laplacian).
I compared `robust_laplacian` with `igl` by the following example for mesh smoothing:

```py
import igl
import numpy as np
import trimesh
from scipy.sparse.linalg import spsolve
import robust_laplacian

geom = trimesh.load("cow.off", process=False)
V = np.array(geom.vertices)
F = np.array(geom.faces)

# Mesh smoothing with libigl
l = igl.cotmatrix(V, F)  # laplace-beltrami operator in libigl
m = igl.massmatrix(V, F, igl.MASSMATRIX_TYPE_BARYCENTRIC) # mass matrix in libigl
s = m - 0.001 * l
smoothed_vertices = spsolve(s, m @ V)

# Mesh smoothing with robust_laplacian
L, M = robust_laplacian.mesh_laplacian(V, F)
s = M - 0.001 * L
smoothed_vertices = spsolve(s, M @ V)
```

How do we implement mesh smoothing with `robust_laplacian`?

## Environment

- Python: `3.8.3`
- trimesh: `3.9.8`
- numpy: `1.18.5`
- scipy: `1.6.3`
- robust-laplacian: `0.1.0`
- igl: latest

## Results

The results are shown as follows.

Original
![image](https://user-images.githubusercontent.com/13940471/119590690-3271b900-be10-11eb-8a6b-eb24062b9fcc.png)

`igl`

![image](https://user-images.githubusercontent.com/13940471/119590669-2a197e00-be10-11eb-965f-29a91e93f6d3.png)

`robust_laplacian`

![image](https://user-images.githubusercontent.com/13940471/119590601-07876500-be10-11eb-9253-1e2033dcec3e.png)

Best regards,

**Comment by nmwsharp** [comment]
Hi! Thanks for the good (and easy to reproduce) questio.

The answer is a sign flip. Unfortunately no one can agree on what sign the Laplacian should have, and the Laplacian built by this library has the opposite sign from the one built by igl. 

Setting `L = -L` for the robust Laplacian should make it work as expected. I'll add a note to the docs explaining.

**Comment by nmwsharp** [comment]
Added note here cd79b49ad10891b084089fe159426a7ae81b75bf

Feel free to reopen with further questions!
